name: 'Setup and Authenticate'
description: 'Sets up Node.js and Authenticates to Google Cloud'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'
  google-credentials:
    description: 'Google Cloud Service Account JSON'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      shell: bash
      run: npm ci

    - name: Authenticate to Google Cloud
      if: ${{ inputs.google-credentials != '' }}
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.google-credentials }}

    - name: Setup Cloud SDK
      if: ${{ inputs.google-credentials != '' }}
      uses: google-github-actions/setup-gcloud@v2
